### ISSUE TITLE
[Signup Data Form] - "In order to receive" left blank error state inconsistent

### ISSUE THREAD

**Issue by mikefantini** [DoSomethingArchive/legacy-website#2167]
If I leave the last question blank on the Thumb Wars request form, it shakes the first time, but it doesn't turn red (like other fiends do). Also if I try again to submit the form with it blank, it doesn't shake a second (or third) time.

Also the error message is odd. The copy appears to be "Thumb Socks with and why it is important to you" (see image), however when I try to copy and paste that error message into this issue it pastes as "We need to know why you signed up." which would work great as copy.

![image](https://cloud.githubusercontent.com/assets/6330971/2998727/436b63ae-dd0e-11e3-99e5-abcc9eddd291.png)

**Comment by DFurnes** [comment]
I have a fix for this on my local Neue. Will push up later tonight.

**Comment by mikefantini** [comment]
sweet thanks!

**Comment by DFurnes** [comment]
Pushed to staging, should be fixed! :sailboat:

**Comment by mikefantini** [comment]
still seeing the bizarre error message and no shake

Again though, when I copy and paste the error message it copy and pasts as "We need to know why you signed up." which would be great, but obviously that's not what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/6330971/3018415/380d776c-df85-11e3-9817-5175061887cc.png)

**Comment by DFurnes** [comment]
Talked through this with Uncle Mike the other night. I misunderstood the issue earlier, it's a problem with how long label text doesn't wrap to a new line correctly. Working on a fix this morning.

**Comment by barryclark** [comment]
Closey close close @DFurnes ?

**Comment by DFurnes** [comment]
:boom:
