### ISSUE TITLE
Client side error messaging on image file size and dimensions

### ISSUE THREAD

**Issue by barryclark** [DoSomethingArchive/legacy-website#3729]
Client side error messaging immediately after file select:
- [x] Dimensions: minimum 480x480, no maximum
- [x] File size: no minimum, 10mb maximum

cc @mikefantini

**Comment by mikefantini** [comment]
Suggested error message copy: "Please upload a larger photo. Min. size is 480px by 480px."

**Comment by sbsmith86** [comment]
@barryclark @mikefantini Do you have an idea of where the error message should show/look like? I have it looking like this right now:

![errormessage](https://cloud.githubusercontent.com/assets/1700409/5880693/802f7d8c-a308-11e4-8b44-fae906b86410.jpg)

**Comment by mikefantini** [comment]
spoke w/ @sbsmith86 in person. We're going to go with this implementation right now and adjust as necessary once we get what it will actually look like up on the site.

**Comment by sbsmith86** [comment]
Client side validation of the image dimensions is done with #3791 .

I will work on the file size limit later. One question I have is if the messaging should be separate for file size and image dimensions or if it should just be one message that fires that covers both errors.

**Comment by mikefantini** [comment]
Thinking about this a bit it seems like it would be confusing if we fire only one message (i.e. can't be too small but can't be too big, but as a user I don't necessarily know whether mine is too small or too big) so I'd recommend we go with two separate messages.

For the too big message let's go with "Please upload a smaller file. The max. size is 2mb."

Speaking of which, I chatted with @mshmsh5000 and the global file limit size set on the site is 10mb, so it seems that the minimum being set here is set somewhere else.

Do we have thoughts on what we want the new minimum to be? @barryclark @weerd @sbsmith86? @DFurnes do we have any error data on what % of report back attempts have failed because of exceeding the file size limit?

**Comment by DFurnes** [comment]
I don't think we have any data on file size validation failures since that's handled by Drupal (not our own client-side validation). From some informal testing on my phone, it looks like a normal iPhone 5S photo is roughly 2MB so I think 10MB is a pretty reasonable limit.

**Comment by barryclark** [comment]
+1 I think that 10MB is fine for now and we could always adjust later if needed.

**Comment by mikefantini** [comment]
sorry @DFurnes @barryclark - just to be clear the current limit on reportbacks is 2MB. Do you guys think we should try to bump it up to 3MB to be safe?

**Comment by barryclark** [comment]
Yep :+1: 

Also I wonder if that could be what's causing #3803 @sbsmith86? Maybe it's over the limit, rather than under?

**Comment by sbsmith86** [comment]
@barryclark no I think that is a separate issue. Right now the only checks on file size are happening on the backend.

**Comment by mshmsh5000** [comment]
Two things.

**Thing one:** Drupal config in prod is not overriding the php.ini max upload size of 10 MB.

![global-upload-limit](https://cloud.githubusercontent.com/assets/149811/5908035/002e15dc-a572-11e4-8319-964f0d507d9a.png)

**Thing two:** I just submitted a pic well over 2.5 MB on stage and prod without generating an error message. Who can reproduce on prod?

**Comment by mikefantini** [comment]
@sbsmith86 didn't you mention the 2MB error originally?

**Comment by sbsmith86** [comment]
@mikefantini @mshmsh5000 Hmm yea i did see this. But i just uploaded a 6MB image on staging and it went through. My local dev will not let me upload 6MB so maybe that's where I saw it. So, if it's only on my dev then I guess this is not an issue. So sorry for all of the confusion here! Always test on staging. Lesson learned.

**Comment by mikefantini** [comment]
Ah got it. Ok sounds good.

So if there is a file size issue (which obviously there shouldn't be given how large it is, but still) let's go with "Please upload a smaller file. The max. size is 10 MB." @sbsmith86

**Comment by mshmsh5000** [comment]
@mikefantini @sbsmith86 Sounds good. And you can pull the effective max file size [from Drupal](https://api.drupal.org/api/drupal/includes%21file.inc/function/file_upload_max_size/7).

**Comment by mikefantini** [comment]
@sbsmith86 are we still missing the max file size error message or is this issue closed now?

**Comment by sbsmith86** [comment]
@mikefantini Yea, we are still missing the max file size error on the client side.

**Comment by aaronschachter** [comment]
I replicated this this morning by reporting on Teens for jeans with a 4 MB jpg.  It takes forever to upload the file after clicking Submit. However I just used the same image on a different campaign, Bake Sale for Babies, and it worked :fries: https://www.dosomething.org/reportback/59374

![screen shot 2015-02-18 at 9 57 44 am](https://cloud.githubusercontent.com/assets/1236811/6252617/a6a6a63c-b769-11e4-9458-6db489ff30f0.png)

**Comment by mshmsh5000** [comment]
This is almost definitely a server-side config problem, where servers have differing file upload and post limits set in php.ini.

/cc @blisteringherb @sergii-tkachenko

**Comment by blisteringherb** [comment]
This should be fixed now.  beta-web3 had the upload_max_filesize set to 2M.  It's now set to 10M to match beta-web1.

**Comment by sbsmith86** [comment]
@blisteringherb amazing!

**Comment by mikefantini** [comment]
@blisteringherb @mshmsh5000 are we able to track any error logs to see if people are still encountering max file size error?

**Comment by sbsmith86** [comment]
Fixed with #4030
