### ISSUE TITLE
Thor Internal Search Does Not Show Images

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/legacy-website#4894]
This page is what is returned when no results are found. It should show images, as it does in production.

![image](https://cloud.githubusercontent.com/assets/12396076/9449925/cb4082ae-4a73-11e5-9fea-dec0d012feb4.png)

No search results (production):
![image](https://cloud.githubusercontent.com/assets/12396076/9449961/f153e846-4a73-11e5-8dea-9f76cf3d08ef.png)

**Comment by ghost** [comment]
@namimody This should be resolved now. The site needed a Drupal Cron run (which there is another ticket for) to actually populate the search functionality. This is fixed now. Please confirm with your login.

<img width="1020" alt="screen shot 2015-08-25 at 12 49 43" src="https://cloud.githubusercontent.com/assets/12188375/9473263/dad120fc-4b27-11e5-8af7-a04ae786d744.png">

**Comment by ghost** [comment]
@namimody Actually, search is fixed. Pictures are still an issue. Addressing that.

**Comment by ghost** [comment]
@namimody Pictures showing up now. They reference www.ds.com for some reason, but they're showing up. I'll work to update the proper references with @blisteringherb later.

**Comment by blisteringherb** [comment]
@sheydari-ds I've reindex all of the items, and now the image URLs are using thor.ds.org. Not sure why they were using www before. The url for the cron job may need adjusting.

**Comment by ghost** [comment]
@sergii-tkachenko Confirmed via Morgan and using Safari that the setup was correct, we just saw browser caching :angry:

**Comment by ghost** [comment]
@namimody This is resolved.

**Comment by sergiitk** [comment]
Confirming this works in Chrome with cmd+r.

**Comment by namimody** [comment]
Hey @sergii-tkachenko and @sheydari-ds  -- I just cleared cache and am still seeing this?

![image](https://cloud.githubusercontent.com/assets/12396076/9475800/f2d69088-4b36-11e5-9af9-8d42bee3c2e4.png)

**Comment by sergiitk** [comment]
Tested on staging:

![image](https://cloud.githubusercontent.com/assets/672669/9502382/8da20ea0-4c39-11e5-96fd-34a101a664c9.png)
