### ISSUE TITLE
Video Field Collection is_empty_alter

### ISSUE THREAD

**Issue by aaronschachter** [DoSomethingArchive/legacy-website#949]
The video field collection needs to implement `hook_field_collection_is_empty_alter`.  

Without this, field_collection_item id's without a video id are still created because there's a default value provided for "Video Provider".

**Comment by barryclark** [comment]
Shipping this one over to @blisteringherb

**Comment by barryclark** [comment]
@blisteringherb @aaronschachter Is this resolved now? I think it is for static content, but not for 11 facts... is that right?

**Comment by aaronschachter** [comment]
Not resolved -- we should not be saving empty `video_id` values in the `field_collection_item` table.  However, I don't think this is necessary for launch because of the changes in #1040, if we're not seeing any more empty youtube videos appear in the other content types.

**Comment by barryclark** [comment]
Thanks @aaronschachter, backlogging.

**Comment by angaither** [comment]
seeing video collections still appear on campaign pages after the video id is removed

refs #5773
